# Generated by Django 4.2.28 on 2026-02-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_catecory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catecory',
            new_name='category',
        ),
    ]
